sudo: required
services:
  - docker

before_install:
  - docker build -t nekoyokoshima/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nekoyokoshima/react-test npm test

after_success:
- docker build -t nekoyokoshima/multi-client ./client
- docker build -t nekoyokoshima/multi-nginx ./nginx
- docker build -t nekoyokoshima/multi-server ./server
- docker build -t nekoyokoshima/multi-worker ./worker
# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take image an dpush to docker hub
- docker push nekoyokoshima/multi-client
- docker push nekoyokoshima/multi-nginx
- docker push nekoyokoshima/multi-server
- docker push nekoyokoshima/multi-worker